<?php

namespace Database\Seeders;

use App\Enums\StatusHallEnum;
use App\Models\Company;
use App\Models\Hall;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HallSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hall::factory()->count(20)->create();

        $halls = [
            [
                'title' => 'Salle Majestic Cotonou',
                'description' => "Située en plein cœur de Cotonou, la Salle Majestic est un espace luxueux pouvant accueillir divers événements comme les mariages, conférences et galas. Elle offre un cadre moderne avec des équipements de pointe, y compris un système de sonorisation haute définition, des jeux de lumières LED et une scène spacieuse.",
                'capacity' => 500,
                'image' => null,
                'address' => 'Carré 2415, Boulevard Steinmetz, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3703,
                'longitude' => 2.3912,
                'website' => 'www.majestic-cotonou.com',
                'price' => 250000,
                'tarification' => "Location journée complète : 250 000 FCFA\nLocation soirée : 180 000 FCFA\nOptions supplémentaires : Décoration (50 000 FCFA), Service traiteur disponible",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Étoile Cotonou',
                'description' => "La Salle Étoile, située à Cotonou, est un lieu d’exception offrant une atmosphère chic et moderne. Idéale pour les événements professionnels ou privés, elle peut accueillir jusqu'à 350 personnes. La salle est équipée d’un système de sonorisation haute qualité et de lumières LED qui s’adaptent à l'ambiance de l'événement. Les grandes fenêtres offrent une vue imprenable sur la ville. Vous pouvez choisir parmi une gamme d'options pour la décoration et le service traiteur, tous personnalisés selon vos besoins. Que ce soit pour des conférences, des mariages ou des soirées d’entreprise, la Salle Étoile saura répondre à toutes vos attentes avec professionnalisme et élégance.",
                'capacity' => 350,
                'image' => null,
                'address' => 'Avenue des Nations Unies, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3675,
                'longitude' => 2.4243,
                'website' => 'www.etoile-cotonou.com',
                'price' => 280000,
                'tarification' => "Location journée : 280 000 FCFA\nLocation soirée : 200 000 FCFA\nOptions supplémentaires :\n- Décoration : 50 000 FCFA\n- Service traiteur : 100 000 FCFA (buffet ou menu personnalisé)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Prestige Porto-Novo',
                'description' => "La Salle Prestige, située à Porto-Novo, est l’un des lieux les plus prisés pour les événements haut de gamme au Bénin. Avec une capacité de 400 personnes, cette salle est parfaitement équipée pour recevoir des mariages, des séminaires et des conférences internationales. Elle dispose d’un grand espace modulable et d’un service traiteur de qualité. Les équipements de sonorisation et d’éclairage sont de dernière génération, permettant de créer une ambiance chaleureuse et élégante. La salle propose également des options de décoration et des forfaits personnalisés pour chaque type d’événement.",
                'capacity' => 400,
                'image' => null,
                'address' => 'Route de l\'aéroport, Porto-Novo, Bénin',
                'city' => 'Porto-Novo',
                'country' => 'Bénin',
                'latitude' => 6.3539,
                'longitude' => 2.6072,
                'website' => 'www.prestige-portonovo.com',
                'price' => 320000,
                'tarification' => "Location journée complète : 320 000 FCFA\nLocation soirée : 250 000 FCFA\nOptions supplémentaires :\n- Décoration personnalisée : 70 000 FCFA\n- Service traiteur : 150 000 FCFA (choix de menu gourmet)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Horizon Abomey-Calavi',
                'description' => "La Salle Horizon est située à Abomey-Calavi, à proximité de Cotonou. C’est un espace idéal pour les événements privés et professionnels. Avec une capacité de 500 personnes, elle est parfaitement adaptée aux conférences, séminaires, et événements communautaires. La salle offre un cadre spacieux et moderne, équipé de technologies de pointe en matière de sonorisation et de projection vidéo. Des options de service traiteur et de décoration sont disponibles, et peuvent être personnalisées pour répondre à tous vos besoins. Les grandes baies vitrées offrent une vue agréable et lumineuse, ce qui donne un cadre naturel et apaisant.",
                'capacity' => 500,
                'image' => null,
                'address' => 'Avenue du Port, Abomey-Calavi, Bénin',
                'city' => 'Abomey-Calavi',
                'country' => 'Bénin',
                'latitude' => 6.4516,
                'longitude' => 2.3626,
                'website' => 'www.horizon-abomeycalavi.com',
                'price' => 250000,
                'tarification' => "Location journée complète : 250 000 FCFA\nLocation soirée : 180 000 FCFA\nOptions supplémentaires :\n- Décoration : 60 000 FCFA\n- Service traiteur : 120 000 FCFA (buffet à volonté)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Bijou Bohicon',
                'description' => "La Salle Bijou, située à Bohicon, est un lieu intime et élégant qui peut accueillir jusqu'à 200 personnes. Idéale pour des événements familiaux comme des mariages, des anniversaires ou des séminaires, elle offre un cadre cosy et moderne. L’équipement de la salle comprend une sonorisation de qualité, un éclairage ajustable et un espace pour les conférences. De plus, un service traiteur est à votre disposition pour offrir des repas personnalisés. La salle se distingue par son atmosphère chaleureuse et son service impeccable, idéal pour des événements à taille humaine.",
                'capacity' => 200,
                'image' => null,
                'address' => 'Avenue des Jeunes, Bohicon, Bénin',
                'city' => 'Bohicon',
                'country' => 'Bénin',
                'latitude' => 7.1883,
                'longitude' => 2.0678,
                'website' => 'www.bijou-bohicon.com',
                'price' => 180000,
                'tarification' => "Location journée complète : 180 000 FCFA\nLocation soirée : 130 000 FCFA\nOptions supplémentaires :\n- Service traiteur : 60 000 FCFA (repas traditionnel ou européen)\n- Décoration : 30 000 FCFA",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Lagon Ouidah',
                'description' => "Située à Ouidah, la Salle Lagon est un endroit idéal pour des événements de grande envergure comme des séminaires, des fêtes d’entreprise ou des cérémonies culturelles. Avec une capacité d’accueil de 600 personnes, cette salle moderne est équipée de toute la technologie nécessaire pour garantir la réussite de votre événement : sonorisation, projection vidéo, éclairage LED, et scène. Un service traiteur est également disponible, offrant des menus adaptés à vos besoins. Que ce soit pour un événement formel ou une soirée plus décontractée, la Salle Lagon s’adapte à toutes les occasions.",
                'capacity' => 600,
                'image' => null,
                'address' => 'Avenue de la Liberté, Ouidah, Bénin',
                'city' => 'Ouidah',
                'country' => 'Bénin',
                'latitude' => 6.3582,
                'longitude' => 2.0834,
                'website' => 'www.lagon-ouidah.com',
                'price' => 350000,
                'tarification' => "Location journée : 350 000 FCFA\nLocation soirée : 270 000 FCFA\nOptions supplémentaires :\n- Service traiteur : 150 000 FCFA (buffet de fruits de mer ou barbecue)\n- Décoration : 80 000 FCFA",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,  // Attribution aléatoire d'une compagnie existante ou création d'une nouvelle
            ],
            [
                'title' => 'Salle Panoramique Cotonou',
                'description' => "La Salle Panoramique est située dans un emplacement privilégié à Cotonou, offrant une vue spectaculaire sur la ville. Avec une capacité de 400 personnes, elle est idéale pour les événements d'envergure, comme les conférences, séminaires et mariages. L'aménagement moderne et l'équipement de haute qualité, notamment un système audio performant et des projecteurs haute définition, garantissent une expérience inoubliable. Les services de traiteur sont disponibles pour tous les types de réceptions.",
                'capacity' => 400,
                'image' => null,
                'address' => 'Avenue Jean-Paul II, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3550,
                'longitude' => 2.4270,
                'website' => 'www.panoramique-cotonou.com',
                'price' => 320000,
                'tarification' => "Location journée : 320 000 FCFA\nLocation soirée : 240 000 FCFA\nOptions supplémentaires :\n- Décoration : 70 000 FCFA\n- Service traiteur : 120 000 FCFA (buffet)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Prestige Cotonou',
                'description' => "La Salle Prestige, située au cœur de Cotonou, est un espace élégant et sophistiqué conçu pour les événements de haut standing. Sa capacité de 500 personnes permet d'accueillir des galas, des mariages ou des congrès de grande envergure. Les équipements modernes, incluant un éclairage LED et un système audio de qualité, ajoutent une touche de luxe à chaque événement. La salle dispose aussi d'une grande scène pour des spectacles ou des présentations.",
                'capacity' => 500,
                'image' => null,
                'address' => 'Quartier Bénin, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3792,
                'longitude' => 2.3695,
                'website' => 'www.prestige-cotonou.com',
                'price' => 350000,
                'tarification' => "Location journée : 350 000 FCFA\nLocation soirée : 260 000 FCFA\nOptions supplémentaires :\n- Décoration : 80 000 FCFA\n- Service traiteur : 150 000 FCFA (menu gourmet)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Oasis Cotonou',
                'description' => "La Salle Oasis, une belle salle moderne à Cotonou, est parfaite pour les événements familiaux et professionnels. Elle dispose d'une capacité d'accueil de 300 personnes. L'équipement audiovisuel, la climatisation et l'option de service traiteur personnalisable en font un lieu idéal pour des fêtes, des séminaires ou des conférences. La salle est entourée de jardins et offre une atmosphère détendue pour les réceptions.",
                'capacity' => 300,
                'image' => null,
                'address' => 'Rue des Jardins, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3733,
                'longitude' => 2.3833,
                'website' => 'www.oasis-cotonou.com',
                'price' => 250000,
                'tarification' => "Location journée : 250 000 FCFA\nLocation soirée : 180 000 FCFA\nOptions supplémentaires :\n- Décoration : 40 000 FCFA\n- Service traiteur : 90 000 FCFA (menu classique)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Royal Cotonou',
                'description' => "La Salle Royal est un espace haut de gamme, situé dans un cadre élégant au centre de Cotonou. Elle offre une capacité d’accueil de 600 personnes et est équipée d’un matériel audiovisuel de pointe pour garantir le succès de vos événements. La salle est idéale pour des mariages, des conférences, des concerts ou des réceptions. Les options de service traiteur sont disponibles pour tous les types d'événements.",
                'capacity' => 600,
                'image' => null,
                'address' => 'Avenue de la République, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3765,
                'longitude' => 2.3919,
                'website' => 'www.royal-cotonou.com',
                'price' => 400000,
                'tarification' => "Location journée : 400 000 FCFA\nLocation soirée : 300 000 FCFA\nOptions supplémentaires :\n- Décoration : 100 000 FCFA\n- Service traiteur : 180 000 FCFA (menu royal)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Grandiose Cotonou',
                'description' => "La Salle Grandiose est l'un des plus grands espaces d'événements à Cotonou. Elle peut accueillir jusqu'à 700 personnes et est idéale pour les grands événements comme les concerts, conférences et cérémonies officielles. La salle dispose de plusieurs équipements modernes, y compris des écrans géants et un système de sonorisation d'exception. Elle offre également des services de sécurité et d'assistance technique pendant toute la durée de l'événement.",
                'capacity' => 700,
                'image' => null,
                'address' => 'Boulevard de la Liberté, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3850,
                'longitude' => 2.4050,
                'website' => 'www.grandiose-cotonou.com',
                'price' => 450000,
                'tarification' => "Location journée : 450 000 FCFA\nLocation soirée : 350 000 FCFA\nOptions supplémentaires :\n- Décoration : 120 000 FCFA\n- Service traiteur : 200 000 FCFA (buffet géant)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Horizon Cotonou',
                'description' => "La Salle Horizon est un espace de taille moyenne situé à Cotonou, parfait pour des séminaires, conférences et événements privés. Elle peut accueillir jusqu'à 250 personnes et offre une vue panoramique sur la ville. Equipée de matériel audiovisuel moderne, la salle est idéale pour des événements qui nécessitent une ambiance calme et professionnelle. Le service traiteur est également disponible pour personnaliser vos réceptions.",
                'capacity' => 250,
                'image' => null,
                'address' => 'Avenue de l’Indépendance, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3666,
                'longitude' => 2.4199,
                'website' => 'www.horizon-cotonou.com',
                'price' => 230000,
                'tarification' => "Location journée : 230 000 FCFA\nLocation soirée : 160 000 FCFA\nOptions supplémentaires :\n- Décoration : 60 000 FCFA\n- Service traiteur : 80 000 FCFA (menu classique)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Majestic Bénin',
                'description' => "La Salle Majestic Bénin est un lieu spacieux et raffiné, adapté pour des événements de grande envergure. Elle peut accueillir jusqu'à 550 personnes et est dotée de tout l'équipement nécessaire pour garantir le succès de vos conférences, salons ou fêtes privées. Le service traiteur est entièrement personnalisé en fonction de vos besoins et la salle est équipée d’un système audiovisuel dernier cri.",
                'capacity' => 550,
                'image' => null,
                'address' => 'Quartier de la Paix, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3700,
                'longitude' => 2.4020,
                'website' => 'www.majestic-benin.com',
                'price' => 380000,
                'tarification' => "Location journée : 380 000 FCFA\nLocation soirée : 290 000 FCFA\nOptions supplémentaires :\n- Décoration : 90 000 FCFA\n- Service traiteur : 160 000 FCFA (menu haut de gamme)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ],
            [
                'title' => 'Salle Elégance Cotonou',
                'description' => "La Salle Elégance est un espace haut de gamme conçu pour des événements privés ou professionnels. Elle peut accueillir jusqu'à 400 personnes et offre un cadre luxueux avec une décoration moderne et sophistiquée. Que ce soit pour un mariage, un séminaire ou un anniversaire, la salle dispose de tout le nécessaire pour un événement réussi : équipement audiovisuel, climatisation, service traiteur personnalisé, etc.",
                'capacity' => 400,
                'image' => null,
                'address' => 'Avenue de la République, Cotonou, Bénin',
                'city' => 'Cotonou',
                'country' => 'Bénin',
                'latitude' => 6.3711,
                'longitude' => 2.3999,
                'website' => 'www.elegance-cotonou.com',
                'price' => 330000,
                'tarification' => "Location journée : 330 000 FCFA\nLocation soirée : 250 000 FCFA\nOptions supplémentaires :\n- Décoration : 85 000 FCFA\n- Service traiteur : 140 000 FCFA (menu élite)",
                'status' =>  StatusHallEnum::AVAILABLE->value,
                'company_id' => Company::inRandomOrder()->first()->id ?? Company::factory()->create()->id,
            ]
            // Ajoute ici 19 autres salles avec des descriptions détaillées
        ];

        foreach ($halls as $hall) {
            Hall::create($hall);
        }
    }
}
